name: Basic CI with Node.js

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Setup Nodejs Environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installing dependencies
        run: npm install

      - name: Run test cases
        run: node test.js